- controllers/treeCtrl.js
> use only label and timestamp as url path

- controllers/treeCtrl.js
- css/style.css
- includes/tree.html
Added the "Create new top concept" button and simplified the tree structure
@eScienceCenter/spacialists
> some tree styling improvements and bugfixing

- lumen/database/seeds/LanguageTableSeeder.php
I've changed the 'short_name' from 'en' to 'gb' for English in order to display the right flag within the dropdown.
> Changed 'short_name' from 'en' to 'gb' for English

- lumen/app/Http/Controllers/TreeController.php
@eScienceCenter/spacialists 
Should fix the non-working "Create sub-concept".
> compare bool as string in post request

- lumen/app/Http/Controllers/TreeController.php
Loading times of the trees should be incredibly faster.
> replace getLabel functions with pg predefined view joins

- controllers/treeCtrl.js
- includes/subTree.html
- includes/tree.html
- lumen/app/Http/Controllers/TreeController.php
- lumen/routes/web.php
Instead of display only the matching concepts, the parent's will be displayed as well. The user can now enter a search term and choose from a list which one they want to edit/open. The tree will select and expand only this element (and all of it's parents).
> Replaced simple js search

- lumen/app/Http/Controllers/TreeController.php
> replace hardcoded table name with variable

- controllers/treeCtrl.js
- lumen/app/Http/Controllers/TreeController.php
Should now be possible to add a new concept to both of the trees.
> fix missing 'isExport' in add new elem functionality

- controllers/treeCtrl.js
- includes/subTree.html
- includes/tree.html
> Show delete menu options only if the element has children

- controllers/treeCtrl.js
> update color on delete/move

- app.js
- controllers/treeCtrl.js
- css/style.css
- includes/tree.html
- index.html
> Stretch divs to full height

- controllers/treeCtrl.js
- lumen/app/Http/Controllers/TreeController.php
- lumen/routes/web.php
> Fix adding/removing labels

- controllers/treeCtrl.js
- includes/subTree.html
- lumen/app/Http/Controllers/TreeController.php
fix #35 
Children should be displayed for all broader concepts. Please review @eScienceCenter/spacialists
> Copy descendants

- lumen/database/migrations/2017_01_11_124832_create_getLabel_views.php
Migration added according to #24.
> Created migration for the views

- controllers/treeCtrl.js
- lumen/app/Http/Controllers/TreeController.php
Fix #36 
This should fix the buggy drag and drop-functionality. Please review @eScienceCenter/spacialists
> Fix drag and drop

- includes/tree.html
> display broader name in export tree's searchbar as well

- lumen/database/migrations/2016_11_09_000000_create_th_concept_table.php
- lumen/database/migrations/2016_11_09_000000_create_th_language_table.php
- lumen/database/migrations/2016_11_09_000001_create_th_broaders_table.php
- lumen/database/migrations/2016_11_09_000001_create_th_concept_label_table.php
See [this issue](https://github.com/eScienceCenter/Spacialist/issues/97) in the Spacialist repo.
> only create (shareable) tables if they not exist

- app/mainService.js
- lumen/app/Http/Controllers/TreeController.php
- lumen/routes/web.php
Fix #66 
Updating (or adding) a label should now update the label in the tree view and the heading.
> update label in tree view if a label has been added/edited

- app/mainService.js
- controllers/treeCtrl.js
- includes/tree.html
> fix dropdown and english flag

- controllers/treeCtrl.js
- includes/tree.html
Fix #65 
Export should now work as expected.
> Fix export

- lumen/app/Http/Controllers/TreeController.php
Fix #73 
Forgot to add label type as condition for counting existing pref labels in added language.
> Check for label type as well

- lumen/app/Http/Controllers/TreeController.php
> get concepts even if they have no label in the desired language

- app/mainService.js
- controllers/treeCtrl.js
Fix #80 
Should now behave as expected. Even in master tree. Please test @derntl
> Top level delete

- app/mainService.js
- controllers/treeCtrl.js
- includes/tree.html
- templates/newConceptModal.html
Fix #89 
Parents should now expand after a new element has been created. Please review @eScienceCenter/spacialists
> expand elements parents after create

- lumen/app/Http/Controllers/TreeController.php
Another fix for broken search. Please review @eScienceCenter/spacialists
> Explicitly define columns

- app/mainService.js
- lumen/app/Http/Controllers/TreeController.php
Fix #89 
If a narrower is added, it is no longer set in the _concept details_ tab.
> Only set added element if expand function is set

- includes/tree.html
> Replaced glyphicons with fa and hide "no results" if search term is too short

- app/mainService.js
- lumen/app/Http/Controllers/TreeController.php
> handle top concepts properly after move from one tree to the other

- app/mainService.js
Fix #98 
Concept Details tab should now be resetted if the selected element gets deleted.
> unset selected element if it gets deleted

- includes/subTree.html
> render entries as table to avoid ugly line breaks

- app.js
- app/mainService.js
- controllers/treeCtrl.js
- css/style.css
- includes/subTree.html
- includes/tree.html
- index.html
- layouts/login.html
- layouts/new-user.html
- roles.html
- user.html
Fix #104, fix #105 and fix #103 
This PR also
- redesigns the login form to match the Spacialist layout
- replaces translation keys with human readable strings
- set the _expand on hover_ while drag&drop to a 500ms timeout, so the tree will no longer expand everything while moving a concept
> some smaller improvements

- app/mainService.js
- includes/tree.html
Small corrections to fix the Upload for RDF-Files.
> fixed upload of rdf files

- CONTRIBUTING.md
- issue_template.md
This PR adds a CONTRIBUTING.md and issue_template.md. All new issues should be created using the issue_template.md file.
> add contributing information

- INSTALL.md
Changes to the INSTALL.md file to reflect deviations if one wants to install ThesauRex into the Spacialist environment.
@eScienceCenter/spacialists please review!
> Install.md to install ThesauRex as part of Spacialist

- controllers/treeCtrl.js
- includes/subTree.html
- lumen/app/Http/Controllers/TreeController.php
- lumen/database/seeds/LanguageTableSeeder.php
Fixes #111 , searching an element now expands all paths to that element in the tree
> Expand tree

- app.js
- layouts/edit-user.html
> add missing editUserModal function

- controllers/treeCtrl.js
- css/style.css
- includes/tree.html
> add toggle for sandbox tree

- lumen/app/Http/Controllers/TreeController.php
Fix #128 
I switched the method of getting concepts (and their labels) from the view based approach to the one used in spacialist. Search and Broader/Narrower lists should be fixed now. Please review @eScienceCenter/spacialists
> fix labels for non-german trees

- bower.json
- css/style.css
- index.html
Fix #115 
This PR adds material design styles and the css patches from Spacialist. Result looks good to me. No glitches or anything like that.
> Add material design

- app/mainService.js
- controllers/treeCtrl.js
- css/style.css
- includes/tree.html
- lumen/app/Http/Controllers/TreeController.php
- lumen/database/migrations/2018_01_29_164204_add_notes_table.php
- lumen/routes/web.php
Fix #123 
This PR adds notes (`skos:note`) to ThesauRex. I also merged pref and alt labels. The first label of a language is now always the preferred labels. All other labels are alt labels. If the first label is deleted, the next one is used as pref label.
> Introduce notes, merge label types
